### ISSUE TITLE
Instantiation of RetryPolicy and CircuitBreaker

### ISSUE THREAD

**Issue by MALPI** [zalando/failsafe-actuator#19]
Add annotation like `@RetryPolicy` in order to inject retry policies as well.

**Comment by MALPI** [comment]
Idea which was discussed with @duergner today is to do it like it's in [Put it to Rest](https://github.com/zalando-stups/put-it-to-rest) project. By defining `RetryPolicy` in `application.properties`.

```
failsafe.policies:
 breaker1:
  retryOn: Class1, Class2
  delay: 1, SECONDS
  maxRetries: 3
```
By this `CircuiBreaker` and `RetryPolicies` could be created easily as Beans and injected via `@Autowired` annotation.
